modLoader="javafml"
loaderVersion="$neo_loader_version_range"
license="$mod_license"
issueTrackerURL="$mod_url_issues"

[[mods]]
modId="$mod_id"
version="$mod_version"
displayName="$mod_name_gloating"
displayURL="$mod_url_source"
logoFile= "logo.png"
credits="$mod_credits"
authors="$mod_authors"
description="""$mod_description"""

[[mixins]]
config="${mod_id}.mixins.json"

# [[mixins]]
# config="${mod_id}.neoforge.compat.mixins.json"

[[dependencies.${mod_id}]] #optional
modId="neoforge"
type="required" #mandatory
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

# The coremods config file path is not configurable and is always loaded from META-INF/coremods.json

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"
